import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { detectPackageManager } from './detect-package-manager'
import { mergeCodexConfigToml } from './mcp-merge'
import { appendGitignore, slugify, writeAgentFiles, writeSkills } from './scaffold-utils'
import {
  agentBuilderToml,
  agentConsultantToml,
  agentExplorerToml,
  agentLeadAsDefaultToml,
  agentLeadToml,
  agentReviewerToml,
  agentsMd,
  featureListJson,
  HEALTH_SH,
} from './templates'

import type { BuildMaterializerOptions, BuildReport, Materializer } from './index'
import type { AgentFileEntry } from './scaffold-utils'
import type { HarnessConfig, Provider, ScaffoldOptions } from '@/types'

/** Agent files this provider owns. Shared by `scaffold()` and `build()`.
 *
 *  `default.toml` is included deliberately. It is a shim that overrides Codex's
 *  built-in `default` agent so `lead` runs when no agent is selected, but it is
 *  still an agent file the user may edit, so it follows the same user-owned
 *  policy as the five roles: created when missing, regenerated only with
 *  --force. */
function codexAgentFiles(config: HarnessConfig): AgentFileEntry[] {
  const projectName = config.project.name
  return [
    { relPath: '.codex/agents/lead.toml', content: agentLeadToml({ projectName }) },
    { relPath: '.codex/agents/explorer.toml', content: agentExplorerToml({ projectName }) },
    { relPath: '.codex/agents/consultant.toml', content: agentConsultantToml({ projectName }) },
    { relPath: '.codex/agents/builder.toml', content: agentBuilderToml({ projectName }) },
    { relPath: '.codex/agents/reviewer.toml', content: agentReviewerToml({ projectName }) },
    { relPath: '.codex/agents/default.toml', content: agentLeadAsDefaultToml({ projectName }) },
  ]
}

export class CodexCliMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — always overwrite (generated from config)
    write('AGENTS.md', agentsMd(config))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    const tasks = opts.firstTask
      ? [{ slug: slugify(opts.firstTask.title), ...opts.firstTask }]
      : []
    write(join(config.storage.dir, 'feature_list.json'), featureListJson(tasks))

    // scope='global' — current.md lives under ~/.harness/dbs/<projectId>/
    // (see resolveGlobalStorageDir in db.ts), not in the project tree, and
    // `markdownFallback.path` doesn't exist on GlobalStorageConfig at all.
    // Skip the local placeholder entirely for that scope.
    if (config.storage.scope === 'local' && !existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .codex/agents/ — user-owned: create when missing, never overwrite
    writeAgentFiles(cwd, codexAgentFiles(config))

    // .codex/config.toml — MERGE, never overwrite whole file. Detect the
    // project's package manager fresh from cwd so the spawned command matches npm/pnpm/yarn.
    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port, cwd, detectPackageManager(cwd))

    appendGitignore(cwd)
    writeSkills(cwd, '.agents/skills')
  }

  async build(config: HarnessConfig, cwd: string, opts: BuildMaterializerOptions = {}): Promise<BuildReport> {
    const write = (relPath: string, content: string) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, 'utf8')
    }

    write('AGENTS.md', agentsMd(config))

    const agents = writeAgentFiles(cwd, codexAgentFiles(config), {
      force: opts.force,
      backupRoot: join(cwd, config.storage.dir, 'backups'),
    })

    // Re-detecting on every build self-corrects the command if the user
    // switched package managers since `ahk init` — no migration flag needed.
    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port, cwd, detectPackageManager(cwd))
    writeSkills(cwd, '.agents/skills')

    return { agents }
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }

  async syncPermissions(_cwd: string): Promise<void> {
    console.log('  Permissions sync not needed for codex-cli — skipping')
  }
}
