import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { detectPackageManager } from './detect-package-manager'
import { mergeCodexConfigToml } from './mcp-merge'
import { appendGitignore, slugify, writeAgentFile, writeSkills } from './scaffold-utils'
import {
  agentBuilderToml,
  agentConsultantToml,
  agentExplorerToml,
  agentLeadAsDefaultToml,
  agentLeadToml,
  agentReviewerToml,
  agentsMd,
  featureListJson,
  HEALTH_SH,
} from './templates'

import type { Materializer } from './index'
import type { HarnessConfig, Provider, ScaffoldOptions } from '@/types'

export class CodexCliMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — always overwrite (generated from config)
    write('AGENTS.md', agentsMd(config))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    const tasks = opts.firstTask
      ? [{ slug: slugify(opts.firstTask.title), ...opts.firstTask }]
      : []
    write(join(config.storage.dir, 'feature_list.json'), featureListJson(tasks))

    if (!existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .codex/agents/ — skip files the dev may have customized
    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')
    const leadModel = config.agents.lead.model
    const explorerModel = config.agents.explorer.model
    const consultantModel = config.agents.consultant?.model
    const builderModel = config.agents.builder.model
    const reviewerModel = config.agents.reviewer.model

    writeAgentFile(cwd, '.codex/agents/lead.toml', agentLeadToml({ projectName, model: leadModel }))
    writeAgentFile(cwd, '.codex/agents/explorer.toml', agentExplorerToml({ projectName, allowedPaths, model: explorerModel }))
    writeAgentFile(cwd, '.codex/agents/consultant.toml', agentConsultantToml({ projectName, model: consultantModel }))
    writeAgentFile(cwd, '.codex/agents/builder.toml', agentBuilderToml({ projectName, writablePaths, model: builderModel }))
    writeAgentFile(cwd, '.codex/agents/reviewer.toml', agentReviewerToml({ projectName, model: reviewerModel }))
    // Override Codex's built-in `default` agent so `lead` runs when no agent is selected
    writeAgentFile(cwd, '.codex/agents/default.toml', agentLeadAsDefaultToml({ projectName, model: leadModel }))

    // .codex/config.toml — MERGE, never overwrite whole file. Detect the
    // project's package manager fresh from cwd so the spawned command matches npm/pnpm/yarn.
    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port, detectPackageManager(cwd))

    appendGitignore(cwd)
    writeSkills(cwd, '.agents/skills')
  }

  async build(config: HarnessConfig, cwd: string): Promise<void> {
    const write = (relPath: string, content: string) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, 'utf8')
    }

    write('AGENTS.md', agentsMd(config))

    const projectName = config.project.name
    const allowedPaths = (config.agents.explorer.allowedPaths ?? []).join(', ')
    const writablePaths = (config.agents.builder.writablePaths ?? []).join(', ')
    const leadModel = config.agents.lead.model
    const explorerModel = config.agents.explorer.model
    const consultantModel = config.agents.consultant?.model
    const builderModel = config.agents.builder.model
    const reviewerModel = config.agents.reviewer.model

    writeAgentFile(cwd, '.codex/agents/lead.toml', agentLeadToml({ projectName, model: leadModel }))
    writeAgentFile(cwd, '.codex/agents/explorer.toml', agentExplorerToml({ projectName, allowedPaths, model: explorerModel }))
    writeAgentFile(cwd, '.codex/agents/consultant.toml', agentConsultantToml({ projectName, model: consultantModel }))
    writeAgentFile(cwd, '.codex/agents/builder.toml', agentBuilderToml({ projectName, writablePaths, model: builderModel }))
    writeAgentFile(cwd, '.codex/agents/reviewer.toml', agentReviewerToml({ projectName, model: reviewerModel }))
    writeAgentFile(cwd, '.codex/agents/default.toml', agentLeadAsDefaultToml({ projectName, model: leadModel }))

    // Re-detecting on every build self-corrects the command if the user
    // switched package managers since `ahk init` — no migration flag needed.
    mergeCodexConfigToml(join(cwd, '.codex/config.toml'), config.tools.mcp.port, detectPackageManager(cwd))
    writeSkills(cwd, '.agents/skills')
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }

  async syncPermissions(_cwd: string): Promise<void> {
    console.log('  Permissions sync not needed for codex-cli — skipping')
  }
}
