import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { renderDelegationGuidance } from './delegation-guidance'
import { detectPackageManager } from './detect-package-manager'
import { mergeGrokConfigToml } from './mcp-merge'
import { appendGitignore, reconcileGeneratedFiles, stampGenerated, writeAgentFiles, writeSkills } from './scaffold-utils'
import { agentBuilder, agentConsultant, agentExplorer, agentLead, agentReviewer, agentsMd, HEALTH_SH, translateFrontmatterForGrok } from './templates'

import type { BuildMaterializerOptions, BuildReport, Materializer } from './index'
import type { AgentFileEntry } from './scaffold-utils'
import type { HarnessConfig, Provider, ScaffoldOptions } from '@/types'

/** Agent files this provider owns. Shared by `scaffold()` and `build()`.
 *
 *  Grok Build's format is markdown + YAML frontmatter, like Claude Code and
 *  OpenCode (unlike Codex's TOML), so agent files land at
 *  `.grok/agents/<role>.md` with `translateFrontmatterForGrok` applying the
 *  provider-native `tools:` allowlist per role. */
function grokAgentFiles(config: HarnessConfig): AgentFileEntry[] {
  const projectName = config.project.name
  return [
    { relPath: '.grok/agents/lead.md', content: translateFrontmatterForGrok(agentLead({ projectName }, '', renderDelegationGuidance('grok-cli', 'lead')), 'lead') },
    { relPath: '.grok/agents/explorer.md', content: translateFrontmatterForGrok(agentExplorer({ projectName }), 'explorer') },
    { relPath: '.grok/agents/consultant.md', content: translateFrontmatterForGrok(agentConsultant({ projectName }), 'consultant') },
    { relPath: '.grok/agents/builder.md', content: translateFrontmatterForGrok(agentBuilder({ projectName }), 'builder') },
    { relPath: '.grok/agents/reviewer.md', content: translateFrontmatterForGrok(agentReviewer({ projectName }), 'reviewer') },
  ]
}

export class GrokMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — fresh project, write unconditionally, but STAMP the provenance
    // marker so the first `ahk build` recognizes it as our own output (a
    // markerless file would look human-edited and freeze config propagation).
    // Grok Build, like OpenCode and Codex CLI, gets no second CLAUDE.md-
    // equivalent file — AGENTS.md is the sole provider-agnostic navigation doc.
    write('AGENTS.md', stampGenerated(agentsMd(config)))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    // .harness/feature_list.json is owned by `runInit`, not the scaffold — it
    // is accumulable user data reconciled via the DB round-trip in init.ts, so
    // the scaffold no longer writes it (which used to clobber a hand-written
    // backlog).

    // scope='global' — current.md lives under ~/.harness/dbs/<projectId>/
    // (see resolveGlobalStorageDir in db.ts), not in the project tree, and
    // `markdownFallback.path` doesn't exist on GlobalStorageConfig at all.
    // Skip the local placeholder entirely for that scope.
    if (config.storage.scope === 'local' && !existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .grok/agents/ — user-owned: create when missing, never overwrite
    writeAgentFiles(cwd, grokAgentFiles(config))

    // .grok/config.toml — MERGE, never overwrite whole file. Native TOML MCP
    // config (task #76 consultant decision — see mergeGrokConfigToml's doc
    // comment for why `.mcp.json` compatibility was rejected). Detect the
    // project's package manager fresh from cwd so the spawned command matches
    // npm/pnpm/yarn.
    mergeGrokConfigToml(join(cwd, '.grok/config.toml'), config.tools.mcp.port, cwd, detectPackageManager(cwd))

    appendGitignore(cwd)

    // .grok/skills/ — provider-namespaced (task #76 consultant decision: matches
    // Grok Build's own native skill-discovery path, and 2 of 3 existing
    // providers — Claude, OpenCode — already namespace their skills dir).
    writeSkills(cwd, '.grok/skills', renderDelegationGuidance('grok-cli', 'coordination-skill'))
  }

  async build(config: HarnessConfig, cwd: string, opts: BuildMaterializerOptions = {}): Promise<BuildReport> {
    // AGENTS.md is DERIVED FROM CONFIG. Reconcile against the provenance marker:
    // untouched files propagate config changes, hand-edited files are preserved
    // (and reported), --force regenerates after backing up.
    const derived = reconcileGeneratedFiles(
      cwd,
      [{ relPath: 'AGENTS.md', content: agentsMd(config) }],
      { force: opts.force, backupRoot: join(cwd, config.storage.dir, 'backups') },
    )

    const agents = writeAgentFiles(cwd, grokAgentFiles(config), {
      force: opts.force,
      backupRoot: join(cwd, config.storage.dir, 'backups'),
    })

    // Re-detecting on every build self-corrects the command if the user
    // switched package managers since `ahk init` — no migration flag needed.
    mergeGrokConfigToml(join(cwd, '.grok/config.toml'), config.tools.mcp.port, cwd, detectPackageManager(cwd))
    writeSkills(cwd, '.grok/skills', renderDelegationGuidance('grok-cli', 'coordination-skill'))

    return { agents, derived }
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }

  async syncPermissions(_cwd: string): Promise<void> {
    console.log('  Permissions sync not needed for grok-cli — skipping')
  }
}
