import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { detectPackageManager } from './detect-package-manager'
import { mergeOpencodeJson } from './mcp-merge'
import { appendGitignore, reconcileGeneratedFiles, stampGenerated, writeAgentFiles, writeSkills } from './scaffold-utils'
import { agentBuilder, agentConsultant, agentExplorer, agentLead, agentReviewer, agentsMd, HEALTH_SH, translateFrontmatterForOpenCode } from './templates'

import type { BuildMaterializerOptions, BuildReport, Materializer } from './index'
import type { AgentFileEntry } from './scaffold-utils'
import type { HarnessConfig, Provider, ScaffoldOptions } from '@/types'

/** Agent files this provider owns. Shared by `scaffold()` and `build()`. */
function opencodeAgentFiles(config: HarnessConfig): AgentFileEntry[] {
  const projectName = config.project.name
  return [
    { relPath: '.opencode/agents/lead.md', content: translateFrontmatterForOpenCode(agentLead({ projectName }), 'lead') },
    { relPath: '.opencode/agents/explorer.md', content: translateFrontmatterForOpenCode(agentExplorer({ projectName }), 'explorer') },
    { relPath: '.opencode/agents/consultant.md', content: translateFrontmatterForOpenCode(agentConsultant({ projectName }), 'consultant') },
    { relPath: '.opencode/agents/builder.md', content: translateFrontmatterForOpenCode(agentBuilder({ projectName }), 'builder') },
    { relPath: '.opencode/agents/reviewer.md', content: translateFrontmatterForOpenCode(agentReviewer({ projectName }), 'reviewer') },
  ]
}

export class OpenCodeMaterializer implements Materializer {
  async scaffold(config: HarnessConfig, opts: ScaffoldOptions): Promise<void> {
    const { cwd } = opts

    const write = (relPath: string, content: string, mode?: number) => {
      const abs = join(cwd, relPath)
      mkdirSync(resolve(abs, '..'), { recursive: true })
      writeFileSync(abs, content, { encoding: 'utf8', mode })
    }

    // AGENTS.md — fresh project, write unconditionally, but STAMP the provenance
    // marker so the first `ahk build` recognizes it as our own output (a
    // markerless file would look human-edited and freeze config propagation).
    write('AGENTS.md', stampGenerated(agentsMd(config)))

    // health.sh — only create if it doesn't exist
    if (!existsSync(join(cwd, 'health.sh'))) {
      write('health.sh', HEALTH_SH, 0o755)
    }

    // .harness/feature_list.json is owned by `runInit`, not the scaffold — it
    // is accumulable user data reconciled via the DB round-trip in init.ts, so
    // the scaffold no longer writes it (which used to clobber a hand-written
    // backlog).

    // scope='global' — current.md lives under ~/.harness/dbs/<projectId>/
    // (see resolveGlobalStorageDir in db.ts), not in the project tree, and
    // `markdownFallback.path` doesn't exist on GlobalStorageConfig at all.
    // Skip the local placeholder entirely for that scope.
    if (config.storage.scope === 'local' && !existsSync(join(cwd, config.storage.markdownFallback.path))) {
      write(
        config.storage.markdownFallback.path,
        `<!-- AUTO-GENERATED by agent-harness-kit — DO NOT EDIT MANUALLY -->\n<!-- Run ahk status to refresh -->\n\n# Current Session\n\nNo tasks in progress.\n`
      )
    }

    // .opencode/agents/ — user-owned: create when missing, never overwrite
    writeAgentFiles(cwd, opencodeAgentFiles(config))

    // opencode.json — MERGE, never overwrite whole file. Detect the project's
    // package manager fresh from cwd so the spawned command matches npm/pnpm/yarn.
    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port, cwd, detectPackageManager(cwd))

    appendGitignore(cwd)
    writeSkills(cwd, '.opencode/skills')
  }

  async build(config: HarnessConfig, cwd: string, opts: BuildMaterializerOptions = {}): Promise<BuildReport> {
    // AGENTS.md is DERIVED FROM CONFIG. Reconcile against the provenance marker:
    // untouched files propagate config changes, hand-edited files are preserved
    // (and reported), --force regenerates after backing up.
    const derived = reconcileGeneratedFiles(
      cwd,
      [{ relPath: 'AGENTS.md', content: agentsMd(config) }],
      { force: opts.force, backupRoot: join(cwd, config.storage.dir, 'backups') },
    )

    const agents = writeAgentFiles(cwd, opencodeAgentFiles(config), {
      force: opts.force,
      backupRoot: join(cwd, config.storage.dir, 'backups'),
    })

    // Re-detecting on every build self-corrects the command if the user
    // switched package managers since `ahk init` — no migration flag needed.
    mergeOpencodeJson(join(cwd, 'opencode.json'), config.tools.mcp.port, cwd, detectPackageManager(cwd))
    writeSkills(cwd, '.opencode/skills')

    return { agents, derived }
  }

  async migrate(config: HarnessConfig, _to: Provider, _cwd: string): Promise<void> {
    void config
  }

  async syncPermissions(_cwd: string): Promise<void> {
    console.log('  Permissions sync not needed for opencode — skipping')
  }
}

